version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

aliases:
  - &node_versions
    - "14.21.3"
    - "16.20.2"
    - "18.16.1"
    - "20.5.1"

parameters:
  node_version:
    type: enum
    default: "18.16.1"
    enum: *node_versions

executors:
  node:
    parameters:
      node_version:
        type: enum
        default: "18.16.1"
        enum: *node_versions
    docker:
      - image: cimg/node:<< parameters.node_version >>-browsers
    working_directory: ~/rentdynamics-js

commands:
  install_dependencies:
    parameters:
      node_version:
        type: string
    steps:
      - restore_cache:
          key: v1-dependencies-<< parameters.node_version >>-{{ checksum "./package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: v1-dependencies-<< parameters.node_version >>-{{ checksum "./package.json" }}
          paths:
            - ./node_modules

  build_project:
    parameters:
      node_version:
        type: string
    steps:
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/rentdynamics-js-<< parameters.node_version >>
          paths:
            - .

  test_project:
    parameters:
      node_version:
        type: string
    steps:
      - attach_workspace:
          at: ~/rentdynamics-js-<< parameters.node_version >>
      - run:
          name: Run tests
          command: npm test

jobs:
  prepare:
    executor: node
    parameters:
      node_version:
        type: enum
        default: "18.16.1"
        enum: *node_versions
    steps:
      - checkout:
          path: ~/rentdynamics-js
      - install_dependencies:
          node_version: << parameters.node_version >>
      - build_project:
          node_version: << parameters.node_version >>

  test:
    executor: node
    parameters:
      node_version:
        type: enum
        default: "18.16.1"
        enum: *node_versions
    steps:
      - test_project:
          node_version: << parameters.node_version >>


  publish-npm:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish package to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

  publish-cdn-dev:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - run:
          name: Publish package to dev cdn
          command: |
            aws s3 cp ./dist/rentdynamics.$(jq .version package.json -r).js s3://$CDNJS_DEV_BUCKET_NAME
            aws s3 cp ./dist/rentdynamics.latest.js s3://$CDNJS_DEV_BUCKET_NAME
            aws cloudfront create-invalidation --distribution-id $CDNJS_DEV_DISTRIBUTION_ID --paths '/*'

  publish-cdn-prod:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - run:
          name: Publish package to cdn
          command: |
            aws s3 cp ./dist/rentdynamics.$(jq .version package.json -r).js s3://$CDNJS_BUCKET_NAME
            aws s3 cp ./dist/rentdynamics.latest.js s3://$CDNJS_BUCKET_NAME
            aws cloudfront create-invalidation --distribution-id $CDNJS_DISTRIBUTION_ID --paths '/*'

workflows:
  test-and-release:
    jobs:
      - prepare:
          matrix:
            parameters:
              node_version: *node_versions

      - test:
          requires:
            - prepare-14.21.3
            - prepare-16.20.2
            - prepare-18.16.1
            - prepare-20.5.1
          matrix:
            parameters:
              node_version: *node_versions

      - publish-npm:
          requires: [test]
          filters:
            branches:
              only:
                - master

      - publish-cdn-dev:
          requires: [test]
          filters:
            branches:
              only:
                - master
                - /^.*__dev$/

      - publish-cdn-prod:
          requires: [publish-npm, publish-cdn-dev]
          filters:
            branches:
              only:
                - master
