version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

executors:
  node:
    docker:
      - image: cimg/node:14-browsers-legacy
        environment:
          NVM_DIR: /opt/circleci/.nvm
    working_directory: ~/rentdynamics-js

jobs:
  prepare:
    executor: node
    steps:
      - checkout:
          path: ~/rentdynamics-js
      - restore_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths: [rentdynamics-js]

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/

      - run: 
          name: Install Node.js versions
          command: |
            nvm install 10
            nvm install 12
            nvm install 14
            nvm install 16
            nvm install 18
            nvm alias default 10

      - run:
          name: Test on Node.js 10
          command: nvm use 10 && npm test

      - run:
          name: Test on Node.js 12
          command: nvm use 12 && npm test

      - run:
          name: Test on Node.js 14
          command: nvm use 14 && npm test

      - run:
          name: Test on Node.js 16
          command: nvm use 16 && npm test

      - run:
          name: Test on Node.js 18
          command: nvm use 18 && npm test 

  publish-npm:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish package to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

  publish-cdn-dev:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - run:
          name: Publish package to dev cdn
          command: |
            aws s3 cp ./dist/rentdynamics.$(jq .version package.json -r).js s3://$CDNJS_DEV_BUCKET_NAME
            aws s3 cp ./dist/rentdynamics.latest.js s3://$CDNJS_DEV_BUCKET_NAME
            aws cloudfront create-invalidation --distribution-id $CDNJS_DEV_DISTRIBUTION_ID --paths '/*'

  publish-cdn-prod:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - run:
          name: Publish package to cdn
          command: |
            aws s3 cp ./dist/rentdynamics.$(jq .version package.json -r).js s3://$CDNJS_BUCKET_NAME
            aws s3 cp ./dist/rentdynamics.latest.js s3://$CDNJS_BUCKET_NAME
            aws cloudfront create-invalidation --distribution-id $CDNJS_DISTRIBUTION_ID --paths '/*'

workflows:
  test-and-release:
    jobs:
      - prepare

      - test:
          requires: [prepare]

      - publish-npm:
          requires: [test]
          filters:
            branches:
              only:
                - master

      - publish-cdn-dev:
          requires: [test]
          filters:
            branches:
              only:
                - master
                - /^.*__dev$/

      - publish-cdn-prod:
          requires: [publish-npm, publish-cdn-dev]
          filters:
            branches:
              only:
                - master
