version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

parameters:
  node_version:
    type: enum
    default: "18"
    enum: ["14", "16", "18", "20"]

executors:
  node:
    docker:
      - image: cimg/node:<< parameters.node_version >>
    working_directory: ~/rentdynamics-js

jobs:
  prepare:
    executor: node
    matrix:
      parameters:
        node_version: ["14", "16", "18", "20"]

    steps:
      - checkout:
          path: ~/rentdynamics-js
      - restore_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths: [rentdynamics-js]

  test:
    executor: node
    matrix:
      parameters:
        node_version: ["14", "16", "18", "20"]
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command: npm test

  publish-npm:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish package to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

  publish-cdn-dev:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - run:
          name: Publish package to dev cdn
          command: |
            aws s3 cp ./dist/rentdynamics.$(jq .version package.json -r).js s3://$CDNJS_DEV_BUCKET_NAME
            aws s3 cp ./dist/rentdynamics.latest.js s3://$CDNJS_DEV_BUCKET_NAME
            aws cloudfront create-invalidation --distribution-id $CDNJS_DEV_DISTRIBUTION_ID --paths '/*'

  publish-cdn-prod:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - run:
          name: Publish package to cdn
          command: |
            aws s3 cp ./dist/rentdynamics.$(jq .version package.json -r).js s3://$CDNJS_BUCKET_NAME
            aws s3 cp ./dist/rentdynamics.latest.js s3://$CDNJS_BUCKET_NAME
            aws cloudfront create-invalidation --distribution-id $CDNJS_DISTRIBUTION_ID --paths '/*'

workflows:
  test-and-release:
    jobs:
      - prepare:

      - test:
          requires: [prepare]

      - publish-npm:
          requires: [test]
          filters:
            branches:
              only:
                - master

      - publish-cdn-dev:
          requires: [test]
          filters:
            branches:
              only:
                - master
                - /^.*__dev$/

      - publish-cdn-prod:
          requires: [publish-npm, publish-cdn-dev]
          filters:
            branches:
              only:
                - master
