version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:10.24.1
    working_directory: ~/rentdynamics-js
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: ./coverage
      - run: ./node_modules/.bin/codecov
